# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

java_version=21
minecraft_version=1.21.11

plugin_version=0.0.4
is_release=false

caffeine_version=3.2.3
worldedit_version=7.4.2-SNAPSHOT
#wierd modrinth version id, used to fetch worldEdit for the run task.
worldEdit_runVersion=p8T2aZ8U