cmd.coin.not-enough-coins=<red>You don't have enough coins!</red>
cmd.coin.set.empty=<red>You not are holding an item.</red>
cmd.coin.set.success=<dark_green>Set coin item successfully to </dark_green><yellow>'</yellow><gold><item></gold><yellow>'</yellow><dark_green>.</dark_green>
cmd.coin.toss.other=<gold><player></gold><dark_green>tossed a coin to </dark_green><gold><other-player></gold><dark_green>.</dark_green>
cmd.coin.toss.self=<gold><player></gold><red> died, by trying to toss themselves a coin.</red>
cmd.error.arg.not-a-number=<red>Argument <yellow>"/<yellow><gold><text></gold><yellow>"</yellow> is not a number!</red>
cmd.error.arg.not-a-player=<red>Argument <yellow>"</yellow><gold><text></gold><yellow>"</yellow> is not a player, or player is not online!</red>
cmd.error.arg.not-enough-args=<red>Not enough Arguments! See <gold>/help <command></gold></red>
cmd.error.arg.unknown=<red>Unknown or wrong argument</red><gold><text></gold><red>!</red>
cmd.error.self-not-a-player=<red>You must be a player to run this command!<red>
cmd.sub.painting.range.success=<dark_green>Range successfully set to </dark_green><gold>'</gold><yellow><number></yellow><gold>'</gold><dark_green> Blocks.</dark_green>
cmd.sub.quotes.add.success=<dark_green>Successfully added a quote with id </dark_green><gold><number></gold><dark_green> to the library: </dark_green><yellow>"</yellow><gold><text></gold><yellow>"</yellow><dark_green>.</dark_green>
cmd.sub.quotes.get.success=The quote with id <gold><number></gold> reads:<newline><gold><text></gold>
cmd.sub.quotes.get.unknown-id=<red>There is no quote with an of id </red><gold><id></gold><red>. Was it deleted?</red>
cmd.sub.quotes.hand.success=<dark_green>Reading quotes requires empty hand: </dark_green><gold><bool></gold>
cmd.sub.quotes.list.entry=<yellow> [</yellow><gold><number></gold><yellow>] - "</yellow><reset><text><yellow>"</yellow>
cmd.sub.quotes.list.header=Quotes
cmd.sub.quotes.remove.no-id=<red>No quote with the id of </red><gold><number></gold><red> exists!</red>
cmd.sub.quotes.remove.success=<dark_green>Successfully removed quote with id:</dark_green> <gold><number></gold>
cmd.sub.quotes.sneak.success=<dark_green>Reading quotes requires sneaking hand: </dark_green><gold><bool></gold>
cmd.sub.reload.success=<green>Reloaded successfully!</green>
list.footer.back=<gold><<( </gold><yellow><number></yellow><gold> )</gold>
list.footer.inner=<dark_green>---<*>---</dark_green>
list.footer.next=<gold>( </gold><yellow><number></yellow><gold> )>></gold>
list.footer.none=<dark_green>-------</dark_green>
list.footer.outer=<dark_green>--</dark_green>
list.header.paged=<gold>-----------{<text> </gold><yellow><number></yellow><gold>/</gold><yellow><max></yellow><gold>}-----------</gold>
list.header.plain=<gold>------------{<text>}------------</gold>
no-permission=<red>You don't have the permission to do that!</red>
prefix=<dark_green>[GreenBook]</dark_green>
wireless.error.receiver.not_wall=<red>Receivers have to be wall signs!</red>
wireless.error.no_network=<red>You can't leave the network blank!</red>
wireless.receiver.created=<dark_green>Wireless receiver successfully created</dark_green>
wireless.transmitter.created=<dark_green>Wireless transmitter successfully created</dark_green>
