main: de.greensurvivors.greenbook.GreenBook
name: GreenBook
description: Like Craftbook, but not a buggy dinosaur
version: 0.0.1-Snapshot
api-version: 1.19
author: GreensurvivorsTeam

commands:
  coin:
    permission-message: Es ist nicht alles Permission, was glänzt.
  greenbook:
    description: The main Command of this plugin.